baseurl = "/"
title = "Alan Doyle"
subTitle = "Life, Linux and everything in between :)"
googleAnalytics = ""
defaultContentLanguage = "en"
paginate = 5

theme = "cleite"
#themesDir = "" # Not necessary on production sites

[permalinks]
  posts = "/blog/:title/"

[params]
    author = "Alan Doyle"
    email = "me@alandoyle.com"
    description = "Alan Doyle's blog ... Life, Linux and everything else."
    favicon = "favicon.ico"
    logo = ""
    custom_css = ["css/custom.css"]
    custom_js = [""]

[params.separator] # Separators between sections on the home page and top menu
    show = true

[params.blog_rss] # Show the RSS feed in the menu bar
    show = true

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Contact"
    link = "contact" # Relative URL

[params.fa] # Font Awesome options
    version = "5.15.4"
    integrity = "sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"

[params.form] # Contact form
    netlify = false
    action = "https://formspree.io/f/xjvzkzao"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = ":date_long"

[params.contact] # Contact info
    email = "me@alandoyle.com"
    phone = ""
    skype = ""
    address = ""

[params.social]
    twitter = "https://twitter.com/_AlanDoyle_"
    facebook = "https://facebook.com/alan.d.doyle"
    github = "https://github.com/alandoyle"
    gitlab = ""
    codepen = ""
    instagram = ""
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[params.copy] # Copyright
    copy = "2008-<NOW> - <TITLE>. All rights reserved." # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[params.languageSwitcher]
    show = false

[languages]
    [languages.en]
        languageName = "en"
        weight = 1
        contentDir = "content/en"
      [languages.de]
        languageName = "de"
        weight = 2
        contentDir = "content/de"
        title = "Das ist der deutsche Titel"
        description = "Das ist die deutsche Beschreibung"
        [languages.de.params]
          [languages.de.params.form] # Translate contact form fields
            inputNameLabel = "Name"
            inputNamePlaceholder = "Dein Name"
            inputEmailLabel = "E-mail"
            inputEmailPlaceholder = "Deine E-Mail-Adresse"
            inputMsgLabel = "Schreib etwas"
            inputSubmitValue = "Abschicken"
            [languages.de.params.cta] # Translate Call To Action
                show = true
                cta = "Kontakt"
                link = "de/kontakt/" # Relative URL
